version: "3.8"

services:
  api-gateway:
    image: frontend
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    networks:
      - api-gateway
    volumes:
      - ./infra/api-gateway/ssl/freshbox.crt:/etc/ssl/certs/freshbox.crt
      - ./infra/api-gateway/ssl/freshbox.key:/etc/ssl/private/freshbox.key

  api-payment:
    image: api-payment
    restart: unless-stopped
    networks:
      - api-gateway

  api-user:
    image: api-user
    restart: unless-stopped
    networks:
      - api-gateway

  api-restaurant:
    image: api-restaurant
    restart: unless-stopped
    networks:
      - api-gateway

  api-order:
    image: api-order
    restart: unless-stopped
    networks:
      - api-gateway

networks:
  api-gateway:
    driver: "bridge"
